###
GET http://localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJJbGhhbSBBbGlmIEZ1cnFvbiIsImVtYWlsIjoiaWxoYW1hbGlwQGdtYWlsLmNvbSIsImlhdCI6MTY2MDcwMDU3MCwiZXhwIjoxNjYwNzg2OTcwfQ.QG4lvq99dR9Yb58waw0AkOQyZ4b8GRawEceaE-zAJ5o

### api register
POST http://localhost:8080/user/registration
Content-Type: application/json

{
    "fullname" : "Ilham Alif Furqon",
    "email" : "ilhamalip@gmail.com",
    "password" : "123456"
}

### api login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email" : "ilhamalip@gmail.com",
    "password" : "123456"
}

### api createpost
POST  http://localhost:8080/post/createpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJJbGhhbSBBbGlmIEZ1cnFvbiIsImVtYWlsIjoiaWxoYW1hbGlwQGdtYWlsLmNvbSIsImlhdCI6MTY2MDcwMDU3MCwiZXhwIjoxNjYwNzg2OTcwfQ.QG4lvq99dR9Yb58waw0AkOQyZ4b8GRawEceaE-zAJ5o

{
    "title" : "Artikel Dua",
    "image" : "askasasas",
    "body" : "LoremIpsumDolor"
}

### api get all post
GET http://localhost:8080/post/getallpost
Content-Type: application/json

### api get one post
GET http://localhost:8080/post/:postId


### api edit post
PUT  http://localhost:8080/post/editpost/:pos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJJbGhhbSBBbGlmIEZ1cnFvbiIsImVtYWlsIjoiaWxoYW1hbGlwQGdtYWlsLmNvbSIsImlhdCI6MTY2MDcwMDU3MCwiZXhwIjoxNjYwNzg2OTcwfQ.QG4lvq99dR9Yb58waw0AkOQyZ4b8GRawEceaE-zAJ5o

{
    "title" : "adadad",
    "image" : "askasasas",
    "body" : "LoremIpsumDolor",
}